# tagが作成されたらrelease/vx.x.xブランチを作成し、releaseブランチにprを作成する
# このPRをマージするとcloudflare wranglerがデプロイする

name: Create Release Branch and PR on Tag

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  pull-requests: write

jobs:
  create_release_pr:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch name
        id: get_branch_name
        run: |
          BRANCH_NAME="release/${{ github.ref_name }}"
          echo "BRANCH_NAME=${BRANCH_NAME}" >> "$GITHUB_OUTPUT"

      - name: Create release branch from tag
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout -b ${{ steps.get_branch_name.outputs.BRANCH_NAME }}
          git push origin ${{ steps.get_branch_name.outputs.BRANCH_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request to release branch
        uses: bakunyo/git-pr-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: release
          GIT_PR_RELEASE_BRANCH_STAGING: ${{ steps.get_branch_name.outputs.BRANCH_NAME }}
          GIT_PR_RELEASE_LABELS: pr-release
          GIT_PR_RELEASE_TEMPLATE: .github/git-pr-release-template.erb
          TZ: Asia/Tokyo
          TAG_NAME: ${{ github.ref_name }}
